### ISSUE TITLE
Have `datalad-make` initialize the git annex remote

### ISSUE THREAD

**Issue by mih** [datalad/datalad-remake#31]
The `git-annex initremote` step is listed as an explicit task for a user in the readme.

I believe that this should be done by datalad-make internally and as-needed. Reasons:

- the particular invocation never changes
- the system does not work without this initialization

A user can only forget it and face errors, or copy the line exactly. A machine should do this IMHO.

**Comment by christian-monch** [comment]
Fixed by #70
