### ISSUE TITLE
Rename `-u, --url-only` flag in `datalad make` command

### ISSUE THREAD

**Issue by m-wierzba** [datalad/datalad-remake#38]
Currently in `datalad make` we have:

```
-u, --url-only        Don't perform the computation, register an URL-key instead. A `git annex get <file>` will trigger the computation.
```

Discussion points:
- This flag is about a _prospective computation_ that is merely registered, rather than executed (the flag name should reflect that).
- Implementation details should not be reflected in the API.

**Comment by christian-monch** [comment]
The option is renamed to `--prospective-execution` in PR #43
